### ISSUE TITLE
Manage files with .txt extension too

### ISSUE THREAD

**Issue by brx75** [cwoac/nvvim#32]
It should be nice if the notes extension could be configurable from .md to something else (.txt i.e.)

**Comment by demure** [comment]
What is the correct way of using these settings from the $HOME/.vimrc?
I have tried to add this to my vimrc, but I'm pretty sure it is being over written on load.

If there is not a way of setting this in the vimrc, I would request this as a feature.
I use vundle to install plugins on multiple machines, so one conf is desirable.

**Comment by cwoac** [comment]
Nope. At the moment they are only read from the file itself.
